Built some plugins to read GDELT files and display as a graph - prett…
constellation-app/constellation-adaptors pull request #10
Opened 2020-08-13 08:37 UTC by canis-majoris-42

…y rudimentary, with not enough thought into ontology. Keen for thoughts.

2020-08-18 01:00 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/utilities/GDELTHoppingUtilities.java
> +                for (String label : labels) {
final

2020-08-18 01:02 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/utilities/GDELTImportingUtilities.java
> +            ZipEntry ze = zis.getNextEntry();
final

2020-08-18 01:02 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/utilities/GDELTImportingUtilities.java
> +        final String day = String.format("%04d%02d%02d", h, m, d);
Surely you could use a convenience function (perhaps alongside a DateTimeFormatter) to do this?

2020-08-18 01:02 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/utilities/GDELTImportingUtilities.java
> +        final String day = String.format("%04d%02d%02d", h, m, d);
Surely you could use a convenience function (perhaps alongside a DateTimeFormatter) to do this?

2020-08-18 01:02 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/utilities/GDELTImportingUtilities.java
> +            ZipEntry ze = zis.getNextEntry();
final

2020-08-18 01:03 UTC, cygnus-x-1 commented
I haven't taken a look at the data model yet, will do so on next review.

2020-08-19 04:12 UTC, canis-majoris-42 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/hopping/HopFromGDELTPlugin.java
> +        return DataAccessPluginAdaptorType.HOP;
Agree - I'll remove the Data Access Adapters Types

2020-08-19 04:13 UTC, canis-majoris-42 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/hopping/HopFromGDELTPlugin.java
> + * RRead graph data from a GDELT file and add it to a graph.
Fixed

2020-08-19 04:13 UTC, canis-majoris-42 commented on AdaptorsDependencies/nbproject/project.xml
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?><project xmlns="http://www.netbeans.org/ns/project/1">
Oops

2020-08-19 04:13 UTC, canis-majoris-42 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/hopping/HopFromGDELTPlugin.java
> +@PluginInfo(pluginType = PluginType.IMPORT, tags = {"HOP"})
Agree - Adjusted

2020-08-19 04:17 UTC, canis-majoris-42 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/hopping/HopFromGDELTPlugin.java
> +        return "Chain on graph entities to import from GDELT";
Agree - adjusted

2020-08-19 04:18 UTC, canis-majoris-42 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/hopping/HopFromGDELTPlugin.java
> +
Removed

2020-08-19 04:19 UTC, canis-majoris-42 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/hopping/HopFromGDELTPlugin.java
> +        final PluginParameter<LocalDateParameterType.LocalDateParameterValue> date = LocalDateParameterType.build(LOCAL_DATE_PARAMETER_ID);
Only in that the files contain a lot of data, and I wanted to limit it to one file at a time to start with.

2020-08-19 04:20 UTC, canis-majoris-42 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/hopping/HopFromGDELTPlugin.java
> +        RecordStore results = null;
Agreed

2020-08-19 04:22 UTC, canis-majoris-42 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/hopping/HopFromGDELTPlugin.java
> +            } catch (IOException ex) {
Yep, agreed

2020-08-19 04:22 UTC, canis-majoris-42 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/hopping/HopFromGDELTPlugin.java
> +        if (results != null) {
Agreed

2020-08-19 04:22 UTC, canis-majoris-42 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/importing/ImportEntitiesFromGDELTPlugin.java
> +        final PluginParameter<LocalDateParameterType.LocalDateParameterValue> date = LocalDateParameterType.build(LOCAL_DATE_PARAMETER_ID);
As mentioned before

2020-08-19 04:25 UTC, canis-majoris-42 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/importing/ImportEntitiesFromGDELTPlugin.java
> +        RecordStore results = null;
Yep

2020-08-19 04:25 UTC, canis-majoris-42 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/importing/ImportEntitiesFromGDELTPlugin.java
> +            } catch (IOException ex) {
Yep

2020-08-19 04:25 UTC, canis-majoris-42 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/importing/ImportEntitiesFromGDELTPlugin.java
> +        if (results != null) {
Yep

2020-08-19 04:25 UTC, canis-majoris-42 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/importing/ImportRelationshipsFromGDELTPlugin.java
> +        final PluginParameter<LocalDateParameterType.LocalDateParameterValue> date = LocalDateParameterType.build(LOCAL_DATE_PARAMETER_ID);
As discussed earlier

2020-08-19 04:27 UTC, canis-majoris-42 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/importing/ImportRelationshipsFromGDELTPlugin.java
> +        RecordStore results = null;
Yep

2020-08-19 04:27 UTC, canis-majoris-42 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/importing/ImportRelationshipsFromGDELTPlugin.java
> +            } catch (IOException ex) {
Yep

2020-08-19 04:27 UTC, canis-majoris-42 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/importing/ImportRelationshipsFromGDELTPlugin.java
> +        if (results != null) {
Yep

2020-08-19 04:27 UTC, canis-majoris-42 commented on branding/modules/org-netbeans-core-windows.jar/org/netbeans/core/windows/view/ui/Bundle.properties
> +#Mon, 21 Jul 2014 16:38:40 +1000
Oops

2020-08-19 04:27 UTC, canis-majoris-42 commented on build.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Oops

2020-08-19 04:28 UTC, canis-majoris-42 commented on constellation.conf
> +# Custom app.conf for CONSTELLATION
Oops

2020-08-19 04:28 UTC, canis-majoris-42 commented on nbproject/build-impl.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Oops

2020-08-19 04:28 UTC, canis-majoris-42 commented on nbproject/genfiles.properties
> +build.xml.data.CRC32=de71a2b5
Oops

2020-08-19 04:28 UTC, canis-majoris-42 commented on nbproject/platform.properties
> +branding.token=constellation
Oops

2020-08-19 04:28 UTC, canis-majoris-42 commented on nbproject/platform.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Oops

2020-08-19 04:28 UTC, canis-majoris-42 commented on nbproject/project.properties
> +app.icon=branding/core/core.jar/org/netbeans/core/startup/frame48.gif
Oops

2020-08-19 04:28 UTC, canis-majoris-42 commented on nbproject/project.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Oops

2020-08-19 04:28 UTC, canis-majoris-42 commented on sonar-project.properties
> +sonar.organization=constellation-app
Agreed

2020-09-02 03:19 UTC, cygnus-x-1 requested changes

2020-09-02 03:19 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/extend/ExtendFromGDELTPlugin.java
> +        MultiChoiceParameterType.setOptions(choices, Arrays.asList(
It might be worth constructing this list around an enum, to make it easier to manage changes in the future.

2020-09-02 03:19 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/extend/ExtendFromGMLPlugin.java
> +                    } catch (IOException ex) {
final

2020-09-02 03:19 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/extend/ExtendFromGMLPlugin.java
> +                            }  catch (ArrayIndexOutOfBoundsException ex) {
final

2020-09-02 03:19 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/extend/ExtendFromGMLPlugin.java
> +                            for (String key : edgeKV.keySet()) {
final

2020-09-02 03:19 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/extend/ExtendFromGMLPlugin.java
> +        HashMap<String, String> edgeKV = new HashMap<>();
final

2020-09-02 03:19 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/extend/ExtendFromGraphMLPlugin.java
> +        HashMap<String,String> nodeAttributes = new HashMap<>();
finals

2020-09-02 03:19 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/extend/ExtendFromGraphMLPlugin.java
> +                    NodeList graphs = documentElement.getElementsByTagName(GRAPH_TAG);
final

2020-09-02 03:19 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/extend/ExtendFromGraphMLPlugin.java
> +                            NodeList children = graph.getChildNodes();
final

2020-09-02 03:19 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/extend/ExtendFromGraphMLPlugin.java
> +                                                    for (String key : transactionAttributes.keySet()) {
final

2020-09-02 03:19 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/extend/ExtendFromGraphMLPlugin.java
> +                                            break;
fix the whitespace

2020-09-02 03:19 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/extend/ExtendFromGraphMLPlugin.java
> +                                            {
unnecessary braces?

2020-09-02 03:19 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/extend/ExtendFromGraphMLPlugin.java
> +                                                for (String key : nodeAttributes.keySet()) {
final

2020-09-02 03:19 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/extend/ExtendFromGraphMLPlugin.java
> +                } catch (FileNotFoundException ex) {
finals

2020-09-02 03:19 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/extend/ExtendFromPajekPlugin.java
> +                                    String[] fields = line.split("\\s+");
final

2020-09-02 03:19 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/extend/ExtendFromPajekPlugin.java
> +                                } catch (ArrayIndexOutOfBoundsException ex) {
final

2020-09-02 03:19 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/extend/ExtendFromPajekPlugin.java
> +                } catch (FileNotFoundException ex) {
finals

2020-09-02 03:19 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/importing/ImportRelationshipsFromGDELTPlugin.java
> +        final PluginParameter<LocalDateParameterType.LocalDateParameterValue> date = LocalDateParameterType.build(LOCAL_DATE_PARAMETER_ID);
Sorry - I couldn't find where you'd answered this...

2020-09-02 03:22 UTC, cygnus-x-1 commented on AdaptorsFunctionality/src/au/gov/asd/tac/constellation/functionality/adaptors/dataaccess/plugins/hopping/HopFromGDELTPlugin.java
> +        final PluginParameter<LocalDateParameterType.LocalDateParameterValue> date = LocalDateParameterType.build(LOCAL_DATE_PARAMETER_ID);
I'm not sure I follow? Why are you using a custom Date parameter over the global Datetime parameter?

2020-09-25 12:53 UTC, merged