Code and copyright updates
constellation-app/constellation-adaptors pull request #33
Opened 2024-04-05 04:00 UTC by Delphinus8821

Updates to Adaptors Data Access Plugins, Functionality and Map View with new code features from the new java versions, general cleanup and copyright updates.

2024-04-07 22:25 UTC, antares1470 approved these changes

2024-04-17 03:47 UTC, OrionsGuardian requested changes

2024-04-17 03:47 UTC, OrionsGuardian commented on AdaptorsDataAccessPlugins/src/au/gov/asd/tac/constellation/views/dataaccess/adaptors/plugins/extend/ExtendFromGraphMLPlugin.java
> +                                        default -> {
Add a comment inside the empty default block.

2024-04-17 03:47 UTC, OrionsGuardian commented on AdaptorsDataAccessPlugins/src/au/gov/asd/tac/constellation/views/dataaccess/adaptors/plugins/extend/ExtendFromGraphMLPlugin.java
> +                                        default -> {
Add a comment inside the empty default block.

2024-04-17 04:30 UTC, OrionsGuardian approved these changes

2024-04-17 04:39 UTC, merged