GDELT Enrichment shouldn't run if no nodes are selected
constellation-app/constellation-adaptors pull request #35
Opened 2024-06-12 06:50 UTC by capricornunicorn123

### Description of the Change

GDELT enrichment trawls through GDELTS database in reverse chronological order to try and retrieve relationships to elements on a graph. It continues to search until the user specified limit of results is reached. If this plugin is run with no selected nodes, then the plugin attempts to search the entire database as the user specified limit is never reached. 

This PR introduces a check to the plugin to skip its execution and report that it was not run in the event that a user tries to run the plugin with 0 nodes selected. 

This plugin still has the possibility to trawl though the database for an undetermined amount of time if the selected node(s) are not referenced or rarely referenced in the database. 

### Benefits
Makes the Plugin more resilient to unintended use

2024-06-13 02:14 UTC, Delphinus8821 approved these changes

2024-06-14 05:18 UTC, antares1470 requested changes

2024-06-14 05:18 UTC, antares1470 commented on AdaptorsDataAccessPlugins/src/au/gov/asd/tac/constellation/views/dataaccess/adaptors/plugins/extend/ExtendFromGDELTPlugin.java
> +            interaction.setProgress(0, 0, "Skipped as no nodes were slected", true);
"selected". could you also add a space before the open curly brace?

2024-06-17 03:26 UTC, antares1470 approved these changes

2024-06-17 03:26 UTC, merged