Updates to Adapters Help Pages
constellation-app/constellation-adaptors pull request #36
Opened 2024-06-13 12:18 UTC by capricornunicorn123

### Description of the Change
This PR adds help pages to Adapter Data Access Plugins.
Specifically, Gaffer and GDELT related plugins have been created. 

### Benefits
Clarifies the proper use of Adapter Data Access Plugins.

2024-06-13 22:45 UTC, Delphinus8821 requested changes

2024-06-13 22:45 UTC, Delphinus8821 commented on AdaptorsDataAccessPlugins/release/modules/ext/docs/AdaptorsDataAccessPlugins/src/au/gov/asd/tac/constellation/views/dataaccess/adaptors/extend-from-gdelt.md
> +Only relationships involving existing and selected nodes on the graph will be imported. Any Entities not currently on the grap will be added.
typo graph

2024-06-13 22:45 UTC, Delphinus8821 commented on AdaptorsDataAccessPlugins/release/modules/ext/docs/AdaptorsDataAccessPlugins/src/au/gov/asd/tac/constellation/views/dataaccess/adaptors/extend-from-gdelt.md
> +To understand moe about GDELT Entities and Relationships in Constellation, see
typo more

2024-06-13 22:45 UTC, Delphinus8821 commented on AdaptorsDataAccessPlugins/release/modules/ext/docs/AdaptorsDataAccessPlugins/src/au/gov/asd/tac/constellation/views/dataaccess/adaptors/import-entities-from-gdelt.md
> +**URL** - A specific point of origin that entity information has been extracted from. Typically, an online publication, forum or site Typically. Contains the attribute:
Grammar is a bit weird in this sentence

2024-06-13 22:45 UTC, Delphinus8821 commented on AdaptorsDataAccessPlugins/release/modules/ext/docs/AdaptorsDataAccessPlugins/src/au/gov/asd/tac/constellation/views/dataaccess/adaptors/import-entities-from-gdelt.md
> +-   Identifier: *Organisation’s Name*
Something weird happens with the ' on this line when viewing it in help

2024-06-13 22:45 UTC, Delphinus8821 commented on AdaptorsDataAccessPlugins/release/modules/ext/docs/AdaptorsDataAccessPlugins/src/au/gov/asd/tac/constellation/views/dataaccess/adaptors/query-from-gaffer.md
> +For this example plugin, a specific example Gaffer data set is required. Please follow the instruction on how to set up and run the <a "https://gchq.github.io/gaffer-doc/v1docs/components/example/roa
This link doesn't work

2024-06-14 05:27 UTC, antares1470 commented on AdaptorsDataAccessPlugins/release/modules/ext/docs/AdaptorsDataAccessPlugins/src/au/gov/asd/tac/constellation/views/dataaccess/adaptors/adaptors-toc.xml
> +                <tocitem text="Extend From GDELT" target="au.gov.asd.tac.constellation.views.dataaccess.adaptors.plugins.extend.ExtendFromGDELTPlugin"/>
Could this TOC item text be "Extend From GDELT Knowledge Graph" to match the name displayed in Data Access View and the title of the help page?

2024-06-16 22:21 UTC, Delphinus8821 approved these changes

2024-06-17 03:26 UTC, antares1470 approved these changes

2024-06-17 03:26 UTC, merged